// Mock data for GatherHub
const categories = [
  { id: 1, name: 'Technology', icon: '💻', color: '#3B82F6' },
  { id: 2, name: 'Sports & Fitness', icon: '🏃', color: '#10B981' },
  { id: 3, name: 'Arts & Culture', icon: '🎨', color: '#8B5CF6' },
  { id: 4, name: 'Food & Drink', icon: '☕', color: '#F59E0B' },
  { id: 5, name: 'Business', icon: '💼', color: '#EF4444' },
  { id: 6, name: 'Music', icon: '🎵', color: '#EC4899' },
  { id: 7, name: 'Language', icon: '🌍', color: '#14B8A6' },
  { id: 8, name: 'Photography', icon: '📷', color: '#6366F1' }
];

const events = [
  {
    id: 1,
    title: 'Web Development Bootcamp',
    description: 'Learn modern web development with React, Node.js, and MongoDB. Perfect for beginners and intermediate developers looking to enhance their skills.',
    date: '2025-07-25',
    time: '18:00',
    location: 'Tech Hub, San Francisco',
    category: 'Technology',
    groupId: 1,
    groupName: 'SF Tech Enthusiasts',
    attendees: 45,
    maxAttendees: 60,
    image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800',
    isOnline: false,
    price: 'Free'
  },
  {
    id: 2,
    title: 'Morning Yoga in the Park',
    description: 'Join us for a refreshing morning yoga session in Golden Gate Park. All levels welcome. Bring your own mat.',
    date: '2025-07-22',
    time: '07:00',
    location: 'Golden Gate Park, San Francisco',
    category: 'Sports & Fitness',
    groupId: 2,
    groupName: 'SF Wellness Warriors',
    attendees: 28,
    maxAttendees: 40,
    image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800',
    isOnline: false,
    price: 'Free'
  },
  {
    id: 3,
    title: 'Art Gallery Opening Night',
    description: 'Exclusive opening of contemporary art exhibition featuring local artists. Wine and appetizers included.',
    date: '2025-07-28',
    time: '19:00',
    location: 'Modern Art Gallery, San Francisco',
    category: 'Arts & Culture',
    groupId: 3,
    groupName: 'Bay Area Art Lovers',
    attendees: 67,
    maxAttendees: 100,
    image: 'https://images.unsplash.com/photo-1561214115-f2f134cc4912?w=800',
    isOnline: false,
    price: '$15'
  },
  {
    id: 4,
    title: 'Coffee Tasting Workshop',
    description: 'Discover the world of specialty coffee. Learn about different brewing methods and taste coffee from around the world.',
    date: '2025-07-26',
    time: '14:00',
    location: 'Artisan Coffee Roasters, San Francisco',
    category: 'Food & Drink',
    groupId: 4,
    groupName: 'Coffee Connoisseurs',
    attendees: 18,
    maxAttendees: 25,
    image: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=800',
    isOnline: false,
    price: '$25'
  },
  {
    id: 5,
    title: 'Startup Pitch Night',
    description: 'Watch emerging startups pitch their ideas to investors. Network with entrepreneurs and VCs.',
    date: '2025-07-30',
    time: '18:30',
    location: 'Innovation Center, San Francisco',
    category: 'Business',
    groupId: 5,
    groupName: 'SF Entrepreneurs Network',
    attendees: 89,
    maxAttendees: 120,
    image: 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=800',
    isOnline: false,
    price: '$20'
  },
  {
    id: 6,
    title: 'Jazz Night Live Performance',
    description: 'Enjoy an evening of smooth jazz with talented local musicians. Full bar and light snacks available.',
    date: '2025-07-27',
    time: '20:00',
    location: 'Blue Note Jazz Club, San Francisco',
    category: 'Music',
    groupId: 6,
    groupName: 'Jazz Lovers Society',
    attendees: 54,
    maxAttendees: 80,
    image: 'https://images.unsplash.com/photo-1511735111819-9a3f7709049c?w=800',
    isOnline: false,
    price: '$30'
  },
  {
    id: 7,
    title: 'Spanish Language Exchange',
    description: 'Practice your Spanish with native speakers in a casual, friendly environment. All levels welcome!',
    date: '2025-07-24',
    time: '19:00',
    location: 'Café Internacional, San Francisco',
    category: 'Language',
    groupId: 7,
    groupName: 'SF Language Learners',
    attendees: 32,
    maxAttendees: 50,
    image: 'https://images.unsplash.com/photo-1546410531-bb4caa6b424d?w=800',
    isOnline: false,
    price: 'Free'
  },
  {
    id: 8,
    title: 'Street Photography Walk',
    description: 'Explore the city streets and capture amazing urban photography. Tips and techniques shared throughout.',
    date: '2025-07-29',
    time: '10:00',
    location: 'Ferry Building, San Francisco',
    category: 'Photography',
    groupId: 8,
    groupName: 'SF Photo Club',
    attendees: 21,
    maxAttendees: 30,
    image: 'https://images.unsplash.com/photo-1452587925148-ce544e77e70d?w=800',
    isOnline: false,
    price: 'Free'
  },
  {
    id: 9,
    title: 'AI & Machine Learning Workshop',
    description: 'Hands-on workshop covering the basics of AI and ML. Build your first neural network!',
    date: '2025-08-02',
    time: '13:00',
    location: 'Online Event',
    category: 'Technology',
    groupId: 1,
    groupName: 'SF Tech Enthusiasts',
    attendees: 156,
    maxAttendees: 200,
    image: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800',
    isOnline: true,
    price: '$40'
  },
  {
    id: 10,
    title: 'Rock Climbing Beginners Session',
    description: 'Learn the basics of indoor rock climbing with certified instructors. All equipment provided.',
    date: '2025-08-01',
    time: '17:00',
    location: 'Climb SF, San Francisco',
    category: 'Sports & Fitness',
    groupId: 2,
    groupName: 'SF Wellness Warriors',
    attendees: 12,
    maxAttendees: 15,
    image: 'https://images.unsplash.com/photo-1522163182402-834f871fd851?w=800',
    isOnline: false,
    price: '$35'
  }
];

const groups = [
  {
    id: 1,
    name: 'SF Tech Enthusiasts',
    description: 'A community of passionate technologists, developers, and innovators exploring the latest in tech.',
    category: 'Technology',
    members: 1248,
    events: 42,
    image: 'https://images.unsplash.com/photo-1531482615713-2afd69097998?w=800',
    location: 'San Francisco, CA',
    founded: '2020-03-15'
  },
  {
    id: 2,
    name: 'SF Wellness Warriors',
    description: 'Dedicated to promoting health, fitness, and wellness through group activities and support.',
    category: 'Sports & Fitness',
    members: 856,
    events: 67,
    image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800',
    location: 'San Francisco, CA',
    founded: '2019-06-22'
  },
  {
    id: 3,
    name: 'Bay Area Art Lovers',
    description: 'Celebrating creativity through gallery visits, art workshops, and cultural events.',
    category: 'Arts & Culture',
    members: 634,
    events: 38,
    image: 'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=800',
    location: 'San Francisco, CA',
    founded: '2018-09-10'
  },
  {
    id: 4,
    name: 'Coffee Connoisseurs',
    description: 'For those who appreciate the art and science of coffee. Tastings, roastery tours, and more.',
    category: 'Food & Drink',
    members: 423,
    events: 29,
    image: 'https://images.unsplash.com/photo-1511920170033-f8396924c348?w=800',
    location: 'San Francisco, CA',
    founded: '2021-01-18'
  },
  {
    id: 5,
    name: 'SF Entrepreneurs Network',
    description: 'Connect with fellow entrepreneurs, share ideas, and build the future together.',
    category: 'Business',
    members: 2134,
    events: 54,
    image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=800',
    location: 'San Francisco, CA',
    founded: '2019-02-05'
  },
  {
    id: 6,
    name: 'Jazz Lovers Society',
    description: 'Experience the best jazz performances and connect with fellow music enthusiasts.',
    category: 'Music',
    members: 567,
    events: 44,
    image: 'https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=800',
    location: 'San Francisco, CA',
    founded: '2020-08-12'
  },
  {
    id: 7,
    name: 'SF Language Learners',
    description: 'Practice languages, meet native speakers, and explore different cultures.',
    category: 'Language',
    members: 945,
    events: 76,
    image: 'https://images.unsplash.com/photo-1523289333742-be1143f6b766?w=800',
    location: 'San Francisco, CA',
    founded: '2019-11-20'
  },
  {
    id: 8,
    name: 'SF Photo Club',
    description: 'Share your passion for photography through photo walks, critiques, and exhibitions.',
    category: 'Photography',
    members: 712,
    events: 51,
    image: 'https://images.unsplash.com/photo-1542038784456-1ea8e935640e?w=800',
    location: 'San Francisco, CA',
    founded: '2020-04-07'
  }
];

const user = {
  id: 1,
  name: 'Alex Johnson',
  email: 'alex.johnson@email.com',
  avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200',
  location: 'San Francisco, CA',
  bio: 'Passionate about technology, fitness, and meeting new people. Always up for a good adventure!',
  interests: ['Technology', 'Sports & Fitness', 'Food & Drink']
};